name: internal-images-push

on:
  schedule:
    - cron:  '0 0 * * 0'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Package all Internal images and push them to Audit ECR
    runs-on: ubuntu-latest
    
    env:
      ECR_REGISTRY: 351409330128.dkr.ecr.ap-south-1.amazonaws.com
      
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: "351409330128"
      - name: Flyway
        run: |
          docker pull flyway/flyway
          docker tag flyway/flyway:latest $ECR_REGISTRY/flyway:latest
          docker push $ECR_REGISTRY/flyway:latest
